### ISSUE TITLE
genupdate videos_in_channels job is failing

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms2jwplayer#32]
From logs:
```
+ sms2jwplayer genupdatejob videos_in_channels --verbose --output=/root/update_job_video_in_channel.json /root/sms_collection_export.csv /root/jwplayer-meta-channel/metadata_000000.json /root/jwplayer-meta-channel/metadata_001000.json /root/jwplayer-meta-channel/metadata_002000.json
INFO:sms2jwplayer.genupdatejob:Loaded metadata for 2283 channels
INFO:sms2jwplayer.genupdatejob:Loaded 2268 CollectionItem item(s) from export
Traceback (most recent call last):
  File "/root/sms2jwplayer/venv/bin/sms2jwplayer", line 11, in <module>
    load_entry_point('sms2jwplayer', 'console_scripts', 'sms2jwplayer')()
  File "/root/sms2jwplayer/sms2jwplayer/__init__.py", line 71, in main
    genupdatejob.main(opts)
  File "/root/sms2jwplayer/sms2jwplayer/genupdatejob.py", line 35, in main
    globals()['process_' + sub_cmd](opts, fobj, items, metadata)
  File "/root/sms2jwplayer/sms2jwplayer/genupdatejob.py", line 194, in process_videos_in_channels
    generic_job_creator(fobj, 'collection', collections, channels, create, update)
  File "/root/sms2jwplayer/sms2jwplayer/genupdatejob.py", line 101, in generic_job_creator
    updates.extend(update(sms_entity, jw_resource))
  File "/root/sms2jwplayer/sms2jwplayer/genupdatejob.py", line 190, in update
    updates.extend(make_videos_in_channels_jobs(collection, 'videos_delete', delete))
  File "/root/sms2jwplayer/sms2jwplayer/genupdatejob.py", line 202, in make_videos_in_channels_jobs
    } for media_id in media_ids]
  File "/root/sms2jwplayer/sms2jwplayer/genupdatejob.py", line 202, in <listcomp>
    } for media_id in media_ids]
ValueError: invalid literal for int() with base 10: ''
```

For the moment, I have commented this out in ``gen_jwplayer_feed.sh`` since we're not really using the collections but this needs fixing.

**Comment by abrahammartin** [comment]
we are not going to do channels in JWPlayer

**Comment by rjw57** [comment]
>  we are not going to do channels in JWPlayer

unfortunately, we still need some support :(
